# Generated by Django 5.1.1 on 2024-09-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('sender', models.CharField(max_length=20)),
                ('receptor', models.IntegerField()),
            ],
        ),
    ]
