# Generated by Django 5.1.1 on 2024-09-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsprovider',
            name='receptor',
            field=models.CharField(default='09056825208', max_length=15),
        ),
    ]
