# Generated by Django 5.1.1 on 2024-09-07 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0002_alter_smsprovider_receptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsprovider',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 12, 22, 21, 59124, tzinfo=datetime.timezone.utc)),
        ),
    ]
