# Generated by Django 5.1.1 on 2024-09-07 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0003_alter_smsprovider_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsprovider',
            name='create',
        ),
        migrations.AddField(
            model_name='smsprovider',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
