# Generated by Django 5.1.1 on 2024-09-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0004_remove_smsprovider_create_smsprovider_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsprovider',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='smsprovider',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
