# Generated by Django 5.1.1 on 2024-09-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0008_alter_smsprovider_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsprovider',
            options={'ordering': ['created', 'message']},
        ),
    ]
