# Generated by Django 5.1.1 on 2024-09-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0014_alter_smsprovider_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsprovider',
            name='receptor',
            field=models.CharField(default='09056825208', max_length=100),
        ),
        migrations.AlterField(
            model_name='smsprovider',
            name='sender',
            field=models.CharField(max_length=100),
        ),
    ]
