# Generated by Django 5.1.1 on 2024-09-08 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0015_alter_smsprovider_receptor_alter_smsprovider_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsprovider',
            name='message',
        ),
        migrations.RemoveField(
            model_name='smsprovider',
            name='receptor',
        ),
        migrations.RemoveField(
            model_name='smsprovider',
            name='created',
        ),
        migrations.RemoveField(
            model_name='smsprovider',
            name='sender',
        ),
        migrations.AddField(
            model_name='smsprovider',
            name='apikey',
            field=models.CharField(default='64667772466B312F6A48414C49637946584A2F36584F64587A6C367A564343723479746467396358726B303D', max_length=100),
        ),
        migrations.AddField(
            model_name='smsprovider',
            name='ctype',
            field=models.CharField(choices=[('token', 'Token'), ('string', 'String')], default='token', max_length=10),
        ),
        migrations.CreateModel(
            name='Smstosend',
            fields=[
                ('smsprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smsapp.smsprovider')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, default='a blanked message', max_length=200)),
                ('receptor', models.CharField(default='09056825208', max_length=100)),
            ],
            bases=('smsapp.smsprovider',),
        ),
    ]
