# Generated by Django 5.1.1 on 2024-09-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0016_remove_smsprovider_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstosend',
            name='receptor',
            field=models.CharField(default='09019610371', max_length=100),
        ),
    ]
